### ISSUE TITLE
Endpoint /todos PUT isn't working correctly

### ISSUE THREAD

**Issue by Glorfi** [PyrozhenkoSerhii/nodejs-for-test-task#1]
https://github.com/PyrozhenkoSerhii/nodejs-for-test-task/blob/a865898a28e925503f55df5170711e634ff4e54a/packages/server/src/main.ts#L150
![image](https://github.com/PyrozhenkoSerhii/nodejs-for-test-task/assets/119957768/b1a232b8-828a-4363-8e44-fb9aceb5e0a5)
Once you try to update "name" or "description", backend returns invalid response with messed-up fields please correct this line so front-end can update a to-do correctly. Thank you!

**Comment by PyrozhenkoSerhii** [comment]
Thanks for the feedback! Done
